FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Copy csproj and restore dependencies (optimises Docker caching)
COPY csharp.csproj ./
RUN dotnet restore "csharp.csproj"

# Copy everything else and build the release
COPY . .
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
